### ISSUE TITLE
Calendar migration schedule

### ISSUE THREAD

**Issue by Tigerfell** [thomersch/OSMCALWikiWidget#3]
As the current "maintainer" of the wiki calendar, I would like to know when you plan to migrate to OSMcal. There seem to be exceptionally few events in the current calendar after 16th December. If the change is done around new year's eve, there will be seven entries to be migrated only and there will be no need for a wiki-hosted 2021 overview of all events.

**Comment by thomersch** [comment]
Switching around new year's eve sounds like a really great idea.

As far as I see, osmcal currently contains all events from the wiki, except for SotM Africa 2021.

There are now at least two places in the wiki which already use osmcal: https://wiki.openstreetmap.org/wiki/Germany and https://wiki.openstreetmap.org/wiki/United_States#Local_OSM_events (Update: https://wiki.openstreetmap.org/wiki/France too)

How do you think we could perform that change? Should Template:Calendar be edited to just contain `<osmcal />`? Along with some comments about the change?

**Comment by Tigerfell** [comment]
> How do you think we could perform that change?
Basically, you change "Template:Calandar" and some translated main pages (I remember the Finish version had a different setup, filtering events in Finland.). I suggest you first announce your steps at https://wiki.osm.org/wiki/Talk:Wiki. You might get some suggestions from there. In addition, you should check with the weekly-osm people if they can use osmcal instead of microformats embedded into the numerous templates called by "Template:Calendar". That might require some work. 

> Should Template:Calendar be edited to just contain <osmcal />?
Yes, it should. "Template:Calendar3" will add the box and some formatting, but I do not think this needs a change. 

> Along with some comments about the change?
I would write down these comments at "Talk:Wiki". Alternatively, you can write a diary entry on osm.org (Minh Nguyen did this when changing the calendar.). There is actually no documentation of the calendar's history in the wiki.

**Comment by thomersch** [comment]
I gave weekly a heads-up in October. They reportedly already have the code for the switch.

For the general public [I just published a diary post](https://www.openstreetmap.org/user/thomersch/diary/395127). I'm a bit anxious to be honest, but we'll see.

Thanks so far for the guidance and feedback, I really appreciate it.

**Comment by thomersch** [comment]
So, there was exactly zero feedback and since osmcal now has significantly more upcoming entries than the wiki, I'll be pulling the trigger soon.

**Comment by thomersch** [comment]
Template:Calendar has been replaced, I'll continue looking at the wiki for broken places.

**Comment by 1ec5** [comment]
So glad that I don’t have to mirror events between multiple OSM calendars anymore! 🎉

I tweaked the template to support the `in` and `lang` parameters with reasonable defaults, so the template can now be reused elsewhere across the wiki with a more familiar syntax and documentation (such as in the visual editor).

**Comment by thomersch** [comment]
> I tweaked the template to support the in and lang parameters with reasonable defaults, so the template can now be reused elsewhere across the wiki with a more familiar syntax and documentation (such as in the visual editor).

That's really awesome, @1ec5, thank you very much!
