### ISSUE TITLE
Wiki message translation

### ISSUE THREAD

**Issue by pyrog** [thomersch/OSMCALWikiWidget#4]
This message in [France](https://wiki.openstreetmap.org/wiki/FR:France) page is not translated. See https://github.com/thomersch/openstreetmap-calendar/issues/57#issuecomment-74955443:

<img width="50%" alt="Add your event to OpenStreetMap Calendar" src="https://user-images.githubusercontent.com/2158081/102751995-26696300-4369-11eb-8b6a-6e08897aa600.png">

The message is hardcoded :
https://github.com/thomersch/OSMCALWikiWidget/blob/d90231ee4c1ce1dfad7b0d5626c6203b8489daaf/includes/OSMCALWidget.php#L49

<br/>

Could you use i.e. [Philipp15b/php-i18n](https://github.com/Philipp15b/php-i18n) ?

Or a simple array ?
```php
$i18n = [
    "de" => "Fügen Sie Ihre Veranstaltung zum OpenStreetMap-Kalender hinzu",
    "en" => "Add your event to OpenStreetMap Calendar",
    "fr" => "Ajoutez votre événement au Calendrier OpenStreetMap",
];

$out .= '<div class="osmcal-banner"><a href="https://osmcal.org/event/add/"><img src="'. $wgExtensionAssetsPath .'/OSMCALWikiWidget/resources/osmcal-icon.png" alt="OSMCAL Logo" width="24" height="24">'
$out .= $i18n[$lang];
$out .= '</div></a>';

```
(PS: sample code not tested)

**Comment by thomersch** [comment]
Mediawiki has its own i18n system. I just added basic support for it in https://github.com/thomersch/OSMCALWikiWidget/commit/7f0120bc49da05c222720406aba4939cd10e932c.

There is one thing I'm not sure about: Whether this will be already picked up correctly on translated pages.

**Comment by thomersch** [comment]
The `lang` attribute (or content language, if available) is considered now, so it looks like this:

<img width="326" alt="Screenshot 2021-01-01 at 14 30 16" src="https://user-images.githubusercontent.com/948605/103439515-e5613080-4c3d-11eb-97d7-11ffb63b1a23.png">

If you want to submit changes to the translations, please look into the [i18n](https://github.com/thomersch/OSMCALWikiWidget/tree/main/i18n) folder.

**Comment by pyrog** [comment]
Thank you 😃
